# -*- coding: utf-8 -*-
"""ASSIGNMENT ONE

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D1r9AEaC-o42ZqGhrIcNOmeAXny5KdTA
"""

import matplotlib.pyplot as plt


x = ["07/2019", "08/2019", "09/2019", "10/2019", "11/2019"]


y1 = [50, 53, 59, 56, 62]
y2 = [39, 47, 42, 51, 51]
y3 = [70, 80, 90, 87, 92]

bar_width = 0.25
x1 = [i - bar_width for i in positions]
x2 = positions
x3 = [i + bar_width for i in positions]
plt.bar(x1, y1, width=bar_width, label="search", color="blue")
plt.bar(x2, y2, width=bar_width, label="direct", color="pink")
plt.bar(x3, y3,  width=bar_width, label="social media", color="yellow" )
plt.xlabel("months")
plt.ylabel("visitors in thousands")
plt.title("visitors by web traffic sources")
plt.xticks(positions, x_labels)
plt.legend()
plt.show()